### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by sveetch** [emencia/django-qr-vcard#1]
https://github.com/emencia/django-qr-vcard/blob/7af83e3effc1234533a62e608dd239f481c78340/qr_vcard/--generate_qr/qrcard.py#L1-L4

So you are using those libraries, it seems you stated they are useful and you started to stand your application on it. It's time to add them as dependencies on your package:

https://github.com/emencia/django-qr-vcard/blob/7af83e3effc1234533a62e608dd239f481c78340/setup.cfg#L28-L29

In fact you should have did it before pushing. Think that if i wanted to clone and try your branch, without related dependencies nothing will work.

You can take some time locally to try some libraries but you should quickly add them in dependencies, even you can lose on this. Imagine you want to reset your local install, you remove everything then clone again your branch and BAM you lose every dependencies, you will have to find them again.

**Comment by Sam-prog-sudo** [comment]
[https://github.com/emencia/django-qr-vcard/commit/1de79cbab535896fe4f528037400891bf66c2b2b#diff-380c6a8ebbbce17d55d50ef17d3cf906](url)

Hi Sveetch,

Thank you for your feedback, I appreciate your concern for this project.
Your comments have been taken into account, and modifications have been made.

__
Sam
