### ISSUE TITLE
Don't mount static directory in application urls

### ISSUE THREAD

**Issue by sveetch** [emencia/django-qr-vcard#14]
https://github.com/emencia/django-qr-vcard/blob/e6a2a86fef73b1477de046ca3fe8049fce05dc42/qr_vcard/urls.py#L12

Applications don't mount static directory url, never. This is the role of Django project to do so, like it has already be done in sandbox:

https://github.com/emencia/django-qr-vcard/blob/e6a2a86fef73b1477de046ca3fe8049fce05dc42/sandbox/urls.py#L20-L21

In a site project there is always an unique static directory and url entry point, this is the same for media directory.

**Comment by Sam-prog-sudo** [comment]
Hi Sveetch,

Your bug report has been duly noted.
Correction is on its way.
