### ISSUE TITLE
Often use Flake for quality

### ISSUE THREAD

**Issue by sveetch** [emencia/django-qr-vcard#2]
Surely, research and development require to quickly try and drop code but code quality is something you have to learn to do automatically.

Use the `make flake` on your current code to see some wrong things. Remember to write beautiful code everytime, it's the best way to gain automatic reflex.

In some months or years when you will have gained quality reflex and then you may some time avoid them for 10minutes to try something.

Thinking "i will fix quality when i'm done" is the best way to never learn quality.

**Comment by Sam-prog-sudo** [comment]
[Linting done.](https://github.com/emencia/django-qr-vcard/commit/f0bc3e7e9626b415e0a89bebd55e534fecacfcc3)
