### ISSUE TITLE
Avoid string concatenations

### ISSUE THREAD

**Issue by sveetch** [emencia/django-qr-vcard#3]
https://github.com/emencia/django-qr-vcard/blob/7af83e3effc1234533a62e608dd239f481c78340/qr_vcard/models/vcard.py#L68-L71

String concatenation can lead to unexpected results and also there are somewhat ugly, avoid them.

You have many other way to join strings.

Like joining with the same string:

```
foo = "ping"
bar = "pong"
"-".join([foo, bar])
```

Or with string format:

```
foo = "ping"
bar = "pong"
"{foo}-{bar}_{plop}".format(foo=foo, bar=bar, plop="burp")
```

Or Fstring:

```
foo = "ping"
bar = "pong"
plop="burp"
f"{foo}-{bar}_{plop}"
```

**Comment by Sam-prog-sudo** [comment]
[Correction done.](https://github.com/emencia/django-qr-vcard/commit/07e84c7fc15634a7dd2cf690a4eeb94816b7e528)
