### ISSUE TITLE
Don't forget to instanciate your callable

### ISSUE THREAD

**Issue by sveetch** [emencia/django-qr-vcard#4]
https://github.com/emencia/django-qr-vcard/blob/7af83e3effc1234533a62e608dd239f481c78340/qr_vcard/models/vcard.py#L77

https://github.com/emencia/django-qr-vcard/blob/7af83e3effc1234533a62e608dd239f481c78340/qr_vcard/models/vcard.py#L87

A callable have to be instanciated to be executed, else you are only referencing the callable, like saying "yep, the hammer is there, right on the ground." when someone asking you to give him the hammer.

So never forget to use callable with the ending `()` and possible arguments in it if any.

Callable are not attributes which does not have to be instanciated. (In fact, further you will learn you can make some callable as object attribute, but for now don't bother about it, callable are not attribute and vice versa).

**Comment by Sam-prog-sudo** [comment]
Issue resolved.
