### ISSUE TITLE
Optional Organization ?

### ISSUE THREAD

**Issue by sveetch** [emencia/django-qr-vcard#5]
https://github.com/emencia/django-qr-vcard/blob/7af83e3effc1234533a62e608dd239f481c78340/qr_vcard/models/vcard.py#L11-L16

Your model is saying "organization is not required", but your code use it without condition:

https://github.com/emencia/django-qr-vcard/blob/7af83e3effc1234533a62e608dd239f481c78340/qr_vcard/models/vcard.py#L70-L71

In this sample, if vcard has a blank organization, generated file name will be something like `martin-dupond-.vcf`. It could lead to issues with overwritten files if there is two "martin dupont".

Also it is rarely a good idea to define a model field as unique (from your Meta.unique_together) on a field which value can be blank.

**Comment by Sam-prog-sudo** [comment]
Issue Resolved.
